### ISSUE TITLE
ModuleNotFoundError: No module named 'flask.ext'

### ISSUE THREAD

**Issue by togakangaroo** [wbolster/flask-uuid#4]
In the docs:

    from flask.ext.uuid import FlaskUUID

but that causes an error. It seems that the package is named `flask_uuid` so

    from flask_uuid import FlaskUUID

seems correct

**Comment by wbolster** [comment]
pull request welcome!

**Comment by wbolster** [comment]
any chance you can make a pr?  (you can even use the github web interface for it)
