### ISSUE TITLE
Breaking when using with Werkzeug V2.2.0

### ISSUE THREAD

**Issue by kartikeyporwal** [wbolster/flask-uuid#7]
This project is breaking when using the latest version of Werkzeug (V2.2.0).

There is changes in the routing module of Werkzeug that does not expose the `ValidationError` that is being imported using [`from werkzeug.routing import BaseConverter, ValidationError`](https://github.com/wbolster/flask-uuid/blob/eb1d3fb01461d5ea037b9f87ce759839aae19c8f/flask_uuid.py#L8).

[`ValidationError`](https://github.com/pallets/werkzeug/blob/e40f1c11ef5610df7ff2eca41170a62dedbd21e7/src/werkzeug/routing/converters.py#L11) can be imported using `from werkzeug.routing.converters import ValidationError`

**Comment by wbolster** [comment]
this project is mostly abandonware tbh. pull request with backward compat import (try/except) welcome!

**Comment by kartikeyporwal** [comment]
It's been fixed in Werkzeug version 2.2.1.
See [1](https://github.com/pgjones/werkzeug/blob/364d9c2a90f02815347c0a998cf0f31ebf6a3ee5/src/werkzeug/routing/__init__.py#L115) and [2](https://github.com/pallets/werkzeug/issues/2465)
